swagger: "2.0"
info:
  description: "This is a documentation of my chat API."
  version: "1.0.0"
  title: "ChatApp"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "messages"
  description: "Message-related operations"
- name: "user"
  description: "User-related operations"
schemes:
- "http"
paths:
  /send:
    post:
      tags:
      - "messages"
      summary: "Send a message"
      description: ""
      operationId: "send"
      consumes:
      - "application/json"
      produces:
      - "text/plain"
      parameters:
      - in: "body"
        name: "message"
        description: "Message definition"
        required: true
        schema:
          $ref: "#/definitions/Message"
      responses:
        "400":
          description: "Invalid input"
        "200":
          description: "Message sent"
            
  /receive:
    get:
      tags:
      - "messages"
      summary: "Receive messages"
      description: ""
      operationId: "receive"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "id"
        description: "User id"
        required: true
        type: "string"
      responses:
        "400":
          description: "Invalid input"
        "200":
          description: "Messages given"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Message"
  /register:
    post:
      tags:
      - "user"
      summary: "Register user"
      description: "This can only be done by the logged in user."
      operationId: "register"
      produces:
      - "text/plain"
      parameters:
      - in: "query"
        name: "id"
        description: "User id"
        required: true
        type: "string"
      responses:
        "400":
          description: "Invalid input"
        "200":
          description: "Succesfully registered"
definitions:
  Message:
    type: "object"
    properties:
      from:
        type: "string"
        example: "you"
      to:
        type: "string"
        example: "me"
      message:
        type: "string"
        example: "Hello there"
    xml:
      name: "Message"